### ISSUE TITLE
您好，请问怎么修改默认的文字颜色呢

### ISSUE THREAD

**Issue by Loki0724** [SheTieJun/wangEditor-Android#2]
editor.setEditorFontColor(Color.RED);这个方法好像不存在

**Comment by SheTieJun** [comment]
> editor.setEditorFontColor(Color.RED);这个方法好像不存在

~ 默认字体 ，它的另外一个意思：不就是第一次设置字体颜色吗，用 editor.setTextColor  试试

**Comment by Loki0724** [comment]
可以了，非常感谢！找了很多富文本编辑器，你这个最好用！666

**Comment by SheTieJun** [comment]
![Snipaste_2023-12-08_17-37-26](https://github.com/SheTieJun/wangEditor-Android/assets/17263560/360a834c-d2b5-4a9b-b74b-c4a1702486d4)
试了一下，你可以改一下assets下的`wang_style.css`   ，写了太久了~太多不记得了

**Comment by SheTieJun** [comment]
> 可以了，非常感谢！找了很多富文本编辑器，你这个最好用！666

(⊙o⊙)…  居然可以，我还以为不行，正常应该改CSS最保险，因为editor.setTextColor必须是要有焦点的时候，才会有效~，看来你的场景可以。这个lib是站在大佬的肩膀上开发的，它的优缺点，我都有在README中说明~ 如果是公司项目慎重选择
